name: fuct
description: Yet another web framework.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
